### ISSUE TITLE
ERROR API

### ISSUE THREAD

**Issue by goldsfinder** [akumanomi1988/WombatDungeonAuto#1]
2024-10-07 20:38:25,846 - INFO - Starting a trip in the dungeons...
Traceback (most recent call last):
  File "D:\bot-testnet\WombatDungeonAuto\wombat_dungeon_api.py", line 39, in _make_request
    response.raise_for_status()
  File "C:\Users\andhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.dungeon.wombat.app/user/dungeon/trip

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\bot-testnet\WombatDungeonAuto\main.py", line 70, in <module>
    main()
  File "D:\bot-testnet\WombatDungeonAuto\main.py", line 44, in main
    trip_response = api.trip(duration_minutes=config['trip_duration_minutes'])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\bot-testnet\WombatDungeonAuto\wombat_dungeon_api.py", line 47, in trip
    return self._make_request("POST", url, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\bot-testnet\WombatDungeonAuto\wombat_dungeon_api.py", line 42, in _make_request
    raise Exception(f"Request error: {e}")
Exception: Request error: 400 Client Error: Bad Request for url: https://api.dungeon.wombat.app/user/dungeon/trip

**Comment by akumanomi1988** [comment]
![image](https://github.com/user-attachments/assets/08605a2d-975d-43a1-a957-76aec50ed4ff)
![image](https://github.com/user-attachments/assets/1fcf4cfb-053e-429d-9fbf-d533529be775)

**Comment by akumanomi1988** [comment]
> 2024-10-07 20:38:25,846 - INFO - Starting a trip in the dungeons... Traceback (most recent call last): File "D:\bot-testnet\WombatDungeonAuto\wombat_dungeon_api.py", line 39, in _make_request response.raise_for_status() File "C:\Users\andhi\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 1024, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.dungeon.wombat.app/user/dungeon/trip
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "D:\bot-testnet\WombatDungeonAuto\main.py", line 70, in main() File "D:\bot-testnet\WombatDungeonAuto\main.py", line 44, in main trip_response = api.trip(duration_minutes=config['trip_duration_minutes']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\bot-testnet\WombatDungeonAuto\wombat_dungeon_api.py", line 47, in trip return self._make_request("POST", url, data) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\bot-testnet\WombatDungeonAuto\wombat_dungeon_api.py", line 42, in _make_request raise Exception(f"Request error: {e}") Exception: Request error: 400 Client Error: Bad Request for url: https://api.dungeon.wombat.app/user/dungeon/trip

![image](https://github.com/user-attachments/assets/08605a2d-975d-43a1-a957-76aec50ed4ff)
![image](https://github.com/user-attachments/assets/1fcf4cfb-053e-429d-9fbf-d533529be775)

have you put the auth into the cookies file?
